/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author smulj
 */
public enum Operacija implements Serializable {
    LOGIN, UCITAJ_CLANOVE, UCITAJ_ZAPOSLENE, DODAJ_ZAPOSLENOG, AZURIRAJ_ZAPOSLENOG, DODAJ_KNJIGU, OBRISI_KNJIGU, UCITAJ_KNJIGE, OBRISI_ZAPOSLENOG, AZURIRAJ_KNJIGU, UCITAJ_KATEGORIJE, OBRISI_KATEGORIJU, DODAJ_KATEGORIJU, AZURIRAJ_KATEGORIJU, UCITAJ_TERMINE, OBRISI_TERMIN, DODAJ_TERMIN, AZURIRAJ_TERMIN,
    OBRISI_CLANA, DODAJ_CLANA, AZURIRAJ_CLANA, UCITAJ_DEZURSTVA, DODAJ_DEZURSTVO, AZURIRAJ_DEZURSTVO, OBRISI_DEZURSTVO,
    UCITAJ_IZNAJMLJIVANJA, DODAJ_IZNAJMLJIVANJE, AZURIRAJ_IZNAJMLJIVANJE, OBRISI_IZNAJMLJIVANJE,
    UCITAJ_STAVKE, DODAJ_STAVKU, AZURIRAJ_STAVKU, OBRISI_STAVKU,
}
