/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.iznajmljivanje;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author smulj
 */
public class PrikaziIznajmljivanjaForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikaziIznajmljivanjaForma
     */
    public PrikaziIznajmljivanjaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIznajmljivanja = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkeIznajmljivanja = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAzurirajIznajmljivanje = new javax.swing.JButton();
        jButtonObrisiIznajmljivanje = new javax.swing.JButton();
        jButtonAzurirajStavku = new javax.swing.JButton();
        jButtonObrisiStavku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonResetuj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldImeZap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jTextFieldPrezimeZap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPrezimeClana = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldImeClana = new javax.swing.JTextField();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIznajmljivanja);

        jTableStavkeIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavkeIznajmljivanja);

        jLabel1.setText("Iznajmljivanja:");

        jLabel2.setText("Stavke selektovanog iznajmljivanja:");

        jButtonAzurirajIznajmljivanje.setText("Azuriraj");

        jButtonObrisiIznajmljivanje.setText("Obrisi");

        jButtonAzurirajStavku.setText("Azuriraj");
        jButtonAzurirajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzurirajStavkuActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setText("Obrisi");

        jLabel3.setText("ID");

        jButtonResetuj.setText("Resetuj pretragu");

        jLabel5.setText("Ime");

        jLabel6.setText("Datum:");

        jLabel7.setText("Prezime");

        jLabel8.setText("dd.MM.yyyy");

        jButtonPretrazi.setText("Pretrazi");

        jLabel9.setText("Zaposleni:");

        jLabel10.setText("Prezime");

        jLabel11.setText("Clan:");

        jLabel12.setText("Ime");

        jTextFieldImeClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeClanaActionPerformed(evt);
            }
        });

        jButtonNazad.setText("Vrati se nazad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNazad)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAzurirajIznajmljivanje)
                                    .addComponent(jButtonObrisiIznajmljivanje))))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAzurirajStavku)
                                    .addComponent(jButtonObrisiStavku))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrezimeZap, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldImeZap, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrezimeClana, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldImeClana, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jButtonPretrazi)
                .addGap(53, 53, 53)
                .addComponent(jButtonResetuj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButtonAzurirajIznajmljivanje)
                                .addGap(64, 64, 64)
                                .addComponent(jButtonObrisiIznajmljivanje))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButtonAzurirajStavku)
                                .addGap(64, 64, 64)
                                .addComponent(jButtonObrisiStavku)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPretrazi)
                            .addComponent(jButtonResetuj))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldImeZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldPrezimeZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldImeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldPrezimeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63)
                .addComponent(jButtonNazad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImeClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeClanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeClanaActionPerformed

    private void jButtonAzurirajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzurirajStavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAzurirajStavkuActionPerformed

     public void addBtnObrisiIznajmljivanjeActionListener(ActionListener actionListener) {
        jButtonObrisiIznajmljivanje.addActionListener(actionListener);
    }
    
    public void addBtnAzurirajIznajmljivanjeActionListener(ActionListener actionListener) {
        jButtonAzurirajIznajmljivanje.addActionListener(actionListener);
    }
    public void addBtnPretraziActionListener(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }
    
    public void addBtnResetujActionListener(ActionListener actionListener) {
        jButtonResetuj.addActionListener(actionListener);
    }
    
    public void addBtnNazadActionListener(ActionListener actionListener) {
        jButtonNazad.addActionListener(actionListener);
    }
    
    public void addBtnObrisiStavkuActionListener(ActionListener actionListener) {
        jButtonObrisiStavku.addActionListener(actionListener);
    }
    
    public void addBtnAzurirajStavkuActionListener(ActionListener actionListener) {
        jButtonAzurirajStavku.addActionListener(actionListener);
    }

    public JButton getjButtonAzurirajIznajmljivanje() {
        return jButtonAzurirajIznajmljivanje;
    }

    public void setjButtonAzurirajIznajmljivanje(JButton jButtonAzurirajIznajmljivanje) {
        this.jButtonAzurirajIznajmljivanje = jButtonAzurirajIznajmljivanje;
    }

    public JButton getjButtonAzurirajStavku() {
        return jButtonAzurirajStavku;
    }

    public void setjButtonAzurirajStavku(JButton jButtonAzurirajStavku) {
        this.jButtonAzurirajStavku = jButtonAzurirajStavku;
    }

    public JButton getjButtonNazad() {
        return jButtonNazad;
    }

    public void setjButtonNazad(JButton jButtonNazad) {
        this.jButtonNazad = jButtonNazad;
    }

    public JButton getjButtonObrisiIznajmljivanje() {
        return jButtonObrisiIznajmljivanje;
    }

    public void setjButtonObrisiIznajmljivanje(JButton jButtonObrisiIznajmljivanje) {
        this.jButtonObrisiIznajmljivanje = jButtonObrisiIznajmljivanje;
    }

    public JButton getjButtonObrisiStavku() {
        return jButtonObrisiStavku;
    }

    public void setjButtonObrisiStavku(JButton jButtonObrisiStavku) {
        this.jButtonObrisiStavku = jButtonObrisiStavku;
    }

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public void setjButtonPretrazi(JButton jButtonPretrazi) {
        this.jButtonPretrazi = jButtonPretrazi;
    }

    public JButton getjButtonResetuj() {
        return jButtonResetuj;
    }

    public void setjButtonResetuj(JButton jButtonResetuj) {
        this.jButtonResetuj = jButtonResetuj;
    }

    public JTable getjTableIznajmljivanja() {
        return jTableIznajmljivanja;
    }

    public void setjTableIznajmljivanja(JTable jTableIznajmljivanja) {
        this.jTableIznajmljivanja = jTableIznajmljivanja;
    }

    public JTable getjTableStavkeIznajmljivanja() {
        return jTableStavkeIznajmljivanja;
    }

    public void setjTableStavkeIznajmljivanja(JTable jTableStavkeIznajmljivanja) {
        this.jTableStavkeIznajmljivanja = jTableStavkeIznajmljivanja;
    }

    public JTextField getjTextFieldDatum() {
        return jTextFieldDatum;
    }

    public void setjTextFieldDatum(JTextField jTextFieldDatum) {
        this.jTextFieldDatum = jTextFieldDatum;
    }

    public JTextField getjTextFieldID() {
        return jTextFieldID;
    }

    public void setjTextFieldID(JTextField jTextFieldID) {
        this.jTextFieldID = jTextFieldID;
    }

    public JTextField getjTextFieldImeClana() {
        return jTextFieldImeClana;
    }

    public void setjTextFieldImeClana(JTextField jTextFieldImeClana) {
        this.jTextFieldImeClana = jTextFieldImeClana;
    }

    public JTextField getjTextFieldImeZap() {
        return jTextFieldImeZap;
    }

    public void setjTextFieldImeZap(JTextField jTextFieldImeZap) {
        this.jTextFieldImeZap = jTextFieldImeZap;
    }

    public JTextField getjTextFieldPrezimeClana() {
        return jTextFieldPrezimeClana;
    }

    public void setjTextFieldPrezimeClana(JTextField jTextFieldPrezimeClana) {
        this.jTextFieldPrezimeClana = jTextFieldPrezimeClana;
    }

    public JTextField getjTextFieldPrezimeZap() {
        return jTextFieldPrezimeZap;
    }

    public void setjTextFieldPrezimeZap(JTextField jTextFieldPrezimeZap) {
        this.jTextFieldPrezimeZap = jTextFieldPrezimeZap;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzurirajIznajmljivanje;
    private javax.swing.JButton jButtonAzurirajStavku;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisiIznajmljivanje;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonResetuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIznajmljivanja;
    private javax.swing.JTable jTableStavkeIznajmljivanja;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldImeClana;
    private javax.swing.JTextField jTextFieldImeZap;
    private javax.swing.JTextField jTextFieldPrezimeClana;
    private javax.swing.JTextField jTextFieldPrezimeZap;
    // End of variables declaration//GEN-END:variables
}
